# Model parameters
context_len_pre: 10
context_len_post: 5
target_len: 2
hidden_dim: 32
hidden_layers: 7
heads: 16
root_pos_hidden_dim: 128
dropout: 0.1
node_features: 6                                  
graph_features: 3                                 
model_path: "checkpoints/baseline.pth"
root_stats_path: "checkpoints/root_stats.npz"

# Dataset parameters
step: 1                                           
batch_size: 2048

# Training parameters
epochs: 200
lr: 0.0001
validation_split: 0.2
patience: 7
root_loss_weight: 0.3
train_data_dir: "data/train"
train_log_path: "results/baseline_train.txt"

# Testing parameters
test_data_dir: "data/test"
test_log_path: "results/baseline_test.txt"
